spring:
  datasource:
    # Configuração para PostgreSQL
    url: jdbc:postgresql://${DATABASE_HOST:viaduct.proxy.rlwy.net}:${DATABASE_PORT:28508}/${DATABASE_NAME:railway}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:dpLeYnJayQucElxbIjugnDyLDkWHurSe}
    driver-class-name: org.postgresql.Driver # Pode ser opcional para H2

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
      dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false


